// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsTNq8FfUh-q1Nk9xhJsvs_YN7VYgHdus',
    appId: '1:246930180418:web:9e51e5357f043459e8e0db',
    messagingSenderId: '246930180418',
    projectId: 'taskflow-pro-f4b57',
    authDomain: 'taskflow-pro-f4b57.firebaseapp.com',
    storageBucket: 'taskflow-pro-f4b57.firebasestorage.app',
    measurementId: 'G-XL1J66J539',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-irydRFFNmtP2Hw_D_w2J1R2vxRqcxE',
    appId: '1:246930180418:android:bb5c247a23aa7cb3e8e0db',
    messagingSenderId: '246930180418',
    projectId: 'taskflow-pro-f4b57',
    storageBucket: 'taskflow-pro-f4b57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR5o76qcbbRBWmxHsRk1ETQe8MfAozi1s',
    appId: '1:246930180418:ios:6cac5af13bb5ca16e8e0db',
    messagingSenderId: '246930180418',
    projectId: 'taskflow-pro-f4b57',
    storageBucket: 'taskflow-pro-f4b57.firebasestorage.app',
    iosBundleId: 'com.example.projectPilotApp',
  );
}
